---
title: "TE - Chapter 11"
output: html_document
date: "2023-02-23"
---
> 1.	Suppose that you are analyzing the effect of universities and colleges opening during a pandemic on increase in the number of positive cases. Name one strategy that you can use to avoid having to collect data on all types of campus characteristic variables that are constant over time that you may have to control for in your analysis.\

Just like they did with individuals in the chapter, we could control for everything about the campus using the fixed effect method. So, we would just add the college's fixed effects to our model. \

> 2.	Intuitively, why would a method that isolates front doors allow you to ignore back doors related to unmeasured variables?\

When we use a method that isolates front doors, we are able to make use of exogenous variation. The cool thing about exogenous variation is that it, in a way, makes the backdoor paths unimportant in our analysis of the data generating process.\

> 3.	On robustness tests:\ 

**a.	What are robustness tests?** \
Test that help us know if we can disprove of an assumption or redoing our analysis in a way that doesn't rely as heavily on that assumption.\

**b.	What is the purpose of conducting a robustness test?** \
This test helps us double-check our assumptions, and amke sure that we are actually articulating the true data generating process.\

**c.	What are placebo tests?**\
This is when we assign a fake treatment to a group that doesn't actually get the treatment. We are hoping the effects will be zero. \

> 4.	Suppose you want to study the effect of attending tutoring sessions on grade point averages (GPA). List at least five variables that impact both attendance of tutoring sessions and students’ GPA. Is it feasible to measure and control for all of the variables?\

- student's previous GPA (could influence them going to a session, but also their GPA after attendance)\
- student's future goals/motivation for better grades\
- family background\
- student's peer group influence\
- parental involvement\
    
I think measure peer group influence might be tough, however... I am not sure it is impossible. \

> 5.	Describe partial identification in your own words.\

In partial identification, instead of getting a single value as the treatment effect estimate, you relax some assumptions and then get a range of values of possible treatment effect estimates. \

> 6.	Pick any causal diagram from the book other than Figure 11.2.\

**a.	Reproduce that diagram here.**\

```{r}
library(ggdag)
library(tidyverse)

dag_coords <-
  tibble(
    name = c("W", "T", "M", "O"),
    x = c(3, 1, 3, 5),
    y = c(2, -1, -1, -1)
  )

p1 <-
  dagify(T ~ W, O ~ W, M ~ T, O ~ M,
    coords = dag_coords
  ) %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_point(color = "blue4", alpha = 1 / 4, size = 7) +
  geom_dag_text(color = "cornflowerblue") +
  geom_dag_edges(edge_color = "blue4") +
  scale_x_continuous(NULL, breaks = NULL, expand = c(0.1, 0.1)) +
  scale_y_continuous(NULL, breaks = NULL, expand = c(0.2, 0.2)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  labs(
    title = "DAG for Question 2")

p1
```

**b.	Select two variables on the diagram without a direct link between them (i.e. no single arrow straight from one of them to the other).**\

I am picking W and M\

The paths to this are \
W -> T -> M\
W -> O <- M\

**c.	What variables would you need to control for that will eliminate any relationship between the two variables (you might not need any).**\
I would need to control for T to eliminate any relationshp. \

**d.	If you looked at the relationship between your two variables from part b, while controlling for the variables from part c, and you got a nonzero result, what would you conclude?**\
This means that either our assumptions are not correct and there is something we left out to characterize their relationship between W and M or that there is some form of measurement error.\


> 7.	What does it mean to say that the effect of financial deregulation on the rate at which firms go bankrupt is “bounded from above” at 2 percentage points?\

d.	The effect is no larger than 2 percentage points\

