---
title: "causal diagrams practice"
output: html_document
date: "2023-02-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

First, let's create the DAG. 
```{r}
library(ggdag)
library(tidyverse)
library(broom)

dag_coords <-
  tibble(
    name = c("X", "E", "C", "B", "A", "D", "Y", "F"),
    x = c(1, 1, 3, 3, 3, 5, 5, 5),
    y = c(4, 1, 8, 6, 4, 10, 4, -1)
  )

p1 <-
  dagify(A ~ E, A ~ X, Y ~ A, Y ~ B, C ~ D, C ~ X, X ~ B,
         F ~ Y, Y ~ D,
    coords = dag_coords
  ) %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_point(color = "blue4", alpha = 1 / 4, size = 7) +
  geom_dag_text(color = "cornflowerblue") +
  geom_dag_edges(edge_color = "blue4") +
  scale_x_continuous(NULL, breaks = NULL, expand = c(0.1, 0.1)) +
  scale_y_continuous(NULL, breaks = NULL, expand = c(0.2, 0.2)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  labs(
    title = "DAG for Class Practice")

p1
```


Now, let's create a simulation that comes from this DAG.

```{r}
makedata <- function (size = 1000, 
                      sd = 0.5, 
                      bX = 3,
                      bE = 2,
                      bA = 2,
                      bB = 10,
                      bC = 5,
                      bD = 2,
                      bY = 3) {
  
  d <- tibble(
    E = rnorm(size, 0, sd),
    B = rnorm(size, 0, sd),
    X = rnorm(size, bB*B, sd),
    C = rnorm(size, bX*X, sd), 
    A = rnorm(size, bE*E + bX*X, sd),
    D = rnorm(size, bC*C, sd), 
    Y = rnorm(size, bA*A + bB*B + bD*D, sd),
    F = rnorm(size, bY*Y, sd)
)
  
  return(d)
}

d <- makedata(size = 10000)
#cor(d)

lm(A ~ E, data = d)


# now lets try to find the total effect of X on Y
# X = 3*2 + 3*5*2 = 36
# B = bB
m1 <- lm(Y ~ X + B,
   data = d)

tidy(m1)
```

class practice

```{r}
# the right answer would be add all the coefficients that get from 
lm(Y ~ X, data = d) %>%  tidy()
```


```{r}
lm(Y ~ X + B, data = d) %>%  tidy()
```
```

